In [7]:
import pandas as pd

f_remonade = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv"
레모네이드 = pd.read_csv(f_remonade)

f_boston = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
보스턴 = pd.read_csv(f_boston)

f_iris = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
아이리스 = pd.read_csv(f_iris)

print("레모네이드", 레모네이드.shape)
print("보스턴", 보스턴.shape)
print("아이리스", 아이리스.shape)

레모네이드 (6, 2)
보스턴 (506, 14)
아이리스 (150, 5)


In [8]:
# 컬럼 확인
print(레모네이드.columns)
print(보스턴.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [9]:
레모네이드

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50

In [10]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


---

## 첫번째 딥러닝 - 레모네이드 판매량 예측

pip install --user tensorflow-gpu==2.5.0

In [ ]:
pip install tensorflow-gpu==2.5.0

In [15]:
# 라이브러리 로딩
import tensorflow as tf 
import pandas as pd

In [16]:
# 데이터를 준비합니다. 
파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv"
레모네이드 = pd.read_csv(파일경로)
print(레모네이드.shape)
print(레모네이드.columns)

독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 2)
Index(['온도', '판매량'], dtype='object')
(6, 1) (6, 1)


In [17]:
# 모델을 준비합니다. 
X = tf.keras.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.Model(X, Y)
model.compile(loss='mse')

In [18]:
model.get_weights()

[array([[1.1953958]], dtype=float32), array([0.], dtype=float32)]

- 기대하는 수식: 판매량 = 2 * 온도
- 초기 상태의 수식: 판매량 = 1.2231315 * 온도 + 0.

In [19]:
# 데이터로 모델을 학습합니다.
model.fit(독립, 종속, epochs=2000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0014
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0014
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0014
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0014
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0014
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0014
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0014


In [20]:
model.get_weights()

[array([[1.9789339]], dtype=float32), array([0.4648029], dtype=float32)]

- Y = W * X + B
- 판매량 = 1.9918023 * 온도 + 0.17365374

In [21]:
# 모델을 이용합니다. 
model.predict(독립)

array([[40.04348 ],
       [42.022415],
       [44.001347],
       [45.98028 ],
       [47.959217],
       [49.93815 ]], dtype=float32)

In [22]:
model.predict([[15]])

array([[30.148813]], dtype=float32)

---

## 두번째 딥러닝 - 보스턴 집값 예측

In [23]:
# 라이브러리 로딩
import tensorflow as tf
import pandas as pd

In [24]:
# 데이터 준비
파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
보스턴 = pd.read_csv(파일경로)
print(보스턴.shape)
print(보스턴.columns)

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
               'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 14)
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
(506, 13) (506, 1)


In [25]:
import tensorflow as tf
 
# 모델 준비
X = tf.keras.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 14        
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [26]:
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense
 
# 모델 준비
X = Input(shape=[13])
Y = Dense(1)(X)
model = Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 14        
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [27]:
# 모델 학습
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 26.4696
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 26.7683
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 26.0711
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 26.6043
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 26.1705
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 26.6077
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 26.7297
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 26.1804
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 26.9564
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 26.2663


In [28]:
model.get_weights()

[array([[-0.08854952],
        [ 0.07141089],
        [-0.05598747],
        [ 3.2411222 ],
        [ 1.6848042 ],
        [ 3.979514  ],
        [ 0.01592343],
        [-0.8776465 ],
        [ 0.14780268],
        [-0.01021563],
        [ 0.01154556],
        [ 0.01509766],
        [-0.58059675]], dtype=float32),
 array([2.520642], dtype=float32)]

In [29]:
# 모델 이용
model.predict(독립[0:5])

array([[28.598019],
       [24.076563],
       [29.738876],
       [29.067299],
       [28.4374  ]], dtype=float32)

In [30]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [31]:
독립[0:5]

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

---

## 세번째 딥러닝 - 아이리스 품종 분류

In [1]:
# 라이브러리 로딩
import tensorflow as tf
import pandas as pd

In [5]:
#데이터 준비
파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

print(아이리스.shape)
print(아이리스.columns)
아이리스


(150, 7)
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [7]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [16]:
# 모델 준비 
X = tf.keras.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.Model(X, Y)
model.compile(loss = 'categorical_crossentropy',
              metrics = 'accuracy')

model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [25]:
# 모델 학습
model.fit(독립, 종속, epochs=1000, verbose=0)
# 1000번 모두 출력 하고 싶지 않을때, verbose=0 => 출력 안함

model.fit(독립, 종속, epochs=10)
# verbose로 출력이 안되었기 때문에, 10번 을 다시 출력해서 얼마나 학습 되었는지 보는 것이다.

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0787 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0787 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0788 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0785 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0788 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0786 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0784 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0793 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0784 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0784 - accuracy: 0.9733


In [28]:
# 모델 이용
sample = 아이리스.sample(5)
print(sample)

model.predict(sample[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']])

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
36    5.5  3.5    1.3   0.2          1              0             0
132   6.4  2.8    5.6   2.2          0              0             1
58    6.6  2.9    4.6   1.3          0              1             0
134   6.1  2.6    5.6   1.4          0              0             1
16    5.4  3.9    1.3   0.4          1              0             0


array([[9.9999952e-01, 4.7030753e-07, 5.4366333e-16],
       [3.6861159e-15, 4.0998147e-03, 9.9590021e-01],
       [3.4398420e-07, 9.7922403e-01, 2.0775653e-02],
       [7.1066707e-12, 1.8004514e-01, 8.1995487e-01],
       [9.9999964e-01, 3.1587456e-07, 4.6168637e-16]], dtype=float32)

---
array([[9.9999952e-01, 4.7030753e-07, 5.4366333e-16] 라면,  
품종_setosa 일 확률이 0.99 ,  
품종_versicolor 확률이 0.00004,  
품종_virginica 확률이 0.00000000000005 로 해석 한다.  

---

In [29]:
# 내 모델의 웨이트 출력
model.get_weights()

[array([[ 1.595938 ,  0.2482983, -1.4605777],
        [ 5.2755775,  0.7589477, -2.2737637],
        [-7.639604 , -1.2206056,  1.7401649],
        [-8.9978285, -2.626638 ,  3.7495   ]], dtype=float32),
 array([ 3.5342026,  2.5710893, -3.1174016], dtype=float32)]

In [39]:
def model_iris(꽃잎길이, 꽃잎폭, 꽃받침길이, 꽃받침폭):
    # 세토사 인지 아닌지 확인하기 위한 수식
    setosa = (1.595938 * 꽃잎길이 
                + -7.639604 * 꽃잎폭 
                + 0.6486535 * 꽃받침길이 
                + -8.9978285 * 꽃받침폭 
                + 3.5342026)

    # 버시컬러 인지 아닌지 확인하기 위한 수식
    versicolor = (0.2482983 * 꽃잎길이
                    + 0.7589477 * 꽃잎폭
                    + -1.2206056 * 꽃받침길이
                    + -2.626638 * 꽃받침폭
                    + 2.5710893)

    # 버지니카 인지 아닌지 확인하기 위한 수식
    virginica = (-1.4605777 * 꽃잎길이
                    + -2.2737637 * 꽃잎폭
                    + 1.7401649 * 꽃받침길이
                    + 3.7495 * 꽃받침폭
                    + -3.1174016)
    
    return setosa, versicolor, virginica

# 위 모델이는 sotmax 과정이 빠져 있음


In [40]:
model_iris(5.2, 2.7, 3.9, 1.4)

(-18.861061850000002, -2.526255789999999, -4.815624520000002)

In [41]:
# 시그모이드 함수 추가.. (맞진 않음)

import math 
def sigmoid(x):
    s = 1 / (1 + math.pow(math.e, -1 * x))
    return s

def model_iris(꽃잎길이, 꽃잎폭, 꽃받침길이, 꽃받침폭):
    # 세토사 인지 아닌지 확인하기 위한 수식
    setosa = (1.595938 * 꽃잎길이 
                + -7.639604 * 꽃잎폭 
                + 0.6486535 * 꽃받침길이 
                + -8.9978285 * 꽃받침폭 
                + 3.5342026)

    # 버시컬러 인지 아닌지 확인하기 위한 수식
    versicolor = (0.2482983 * 꽃잎길이
                    + 0.7589477 * 꽃잎폭
                    + -1.2206056 * 꽃받침길이
                    + -2.626638 * 꽃받침폭
                    + 2.5710893)

    # 버지니카 인지 아닌지 확인하기 위한 수식
    virginica = (-1.4605777 * 꽃잎길이
                    + -2.2737637 * 꽃잎폭
                    + 1.7401649 * 꽃받침길이
                    + 3.7495 * 꽃받침폭
                    + -3.1174016)
    
    s = (setosa + versicolor + virginica)
    setosa = setosa / s
    versicolor = versicolor / s
    virginica = virginica / s
    
    return setosa, versicolor, virginica

In [42]:
model_iris( 5.5, 2.4, 3.8, 1.1)

(0.6378465957714998, 0.08387425287668819, 0.27827915135181197)

---

In [ ]:
# 모델 구조 만들기
X = tf.keras.layers.Input(shape=[13])
# 히든레이어                                           (relu 는 구식..)
H = tf.keras.layers.Dense(5, activation='swish')(X) # swish 는 최근 성능이 좋은 활성화 함수
# 히든 추가
H = tf.keras.layers.Dense(3, activation='swish')(H)
H = tf.keras.layers.Dense(3, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

---

# 네번째 딥러닝 - 히든레이어 실습


In [43]:
import pandas as pd 
import tensorflow as tf

# 데이터 준비
파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
보스턴 = pd.read_csv(파일경로)
print(보스턴.shape)
print(보스턴.columns)

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
               'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)
보스턴.head()

(506, 14)
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
(506, 13) (506, 1)


crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [44]:
# 모델 준비
X = tf.keras.Input(shape=[13])
H = tf.keras.layers.Dense(5, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 70        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 6         
Total params: 76
Trainable params: 76
Non-trainable params: 0
_________________________________________________________________


In [45]:
# 모델 학습
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 3ms/step - loss: 16.1508
Epoch 2/10
16/16 [==============================] - 0s 3ms/step - loss: 16.2771
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 16.0161
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 16.0617
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 15.8533
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 15.7903
Epoch 7/10
16/16 [==============================] - 0s 5ms/step - loss: 15.9274
Epoch 8/10
16/16 [==============================] - 0s 4ms/step - loss: 16.1058
Epoch 9/10
16/16 [==============================] - 0s 3ms/step - loss: 16.0889
Epoch 10/10
16/16 [==============================] - 0s 4ms/step - loss: 15.8567
